core/accounts/urls.py
from django.urls import path, include
from accounts.views import UserRegisterView, UserLoginView
from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    # Task list view
    path("register/",UserRegisterView.as_view(), name="register"),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page="/"), name='logout'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('song.urls')),
    path('accounts/',include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/song/urls.py
from django.urls import path, include
from song.views import HomeList, PlaySong, ChoiceArtist, AllSong, Searchview

app_name = "song"

urlpatterns = [
    # Task list view
    path("", HomeList.as_view(), name="home"),
    path('all_song/', AllSong.as_view(), name='all_song'),
    path('artist-choice/<int:artist_id>/', ChoiceArtist.as_view(), name='artist_choice'),
    path('play_song/<int:pk>/', PlaySong.as_view(), name='play_song'),
    path('search/',Searchview.as_view(),name ='search'),
    # path('createartist/',ArtistCreateView.as_view(),name="artist_create"),
    # path('createsong/',SongCreateView.as_view(),name="song_create")
]

core/accounts/models.py
from django.db import models

# Create your models here.

core/song/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext as _
from django.db.models.fields.files import ImageFieldFile
from PIL import Image
from io import BytesIO
from django.core.files import File
from django.conf import settings
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from .tools import UploadToPathAndRename
def get_image_field(self):
    output = []
    for k, v in self.__dict__.items():
        if isinstance(v, ImageFieldFile):
            output.append(k)
    return output


class MainModel(models.Model):
    create_date = models.DateTimeField(auto_now_add=True, blank=True, null=True, verbose_name=_("create date"))
    modify_date = models.DateTimeField(auto_now=True, blank=True, null=True, verbose_name=_("modify date"))
    is_active = models.BooleanField(default=True, verbose_name=_("is active"))

    def save(self, *args, **kwargs):
        image_fields = get_image_field(self)
        if image_fields:
            for i in image_fields:
                if hasattr(self, i) and isinstance(getattr(self, i), ImageFieldFile):
                    image = Image.open(getattr(self, i).file)
                    image_io = BytesIO()
                    image_extension = getattr(self, i).name.rpartition(".")[-1].upper()
                    image_extension = "JPEG" if image_extension == "JPG" else image_extension
                    image.save(image_io, image_extension, quality=60)
                    new_image = File(image_io, name=getattr(self, i).name)
                    setattr(self, i, new_image)
        self.full_clean()
        super().save(*args, **kwargs)

    class Meta:
        abstract = True

class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name


class Artist(MainModel):
    image = models.ImageField(upload_to=UploadToPathAndRename("artist"),default='artist/default.jpg')
    name = models.CharField(max_length=255)
    status =models.BooleanField(default= False)
    
    def __str__(self):
        return self.name
    
class Song(models.Model):
    image = models.ImageField(upload_to=UploadToPathAndRename("song"),default='song/default.jpg')
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True, related_name='song_author')
    artist = models.ForeignKey(Artist, on_delete= models.CASCADE, related_name="relate_song")
    audio = models.FileField(blank=True,null=True)
    lyric = models.TextField(null=True , blank = True)
    category = models.ManyToManyField(Category)
    count_view = models.IntegerField(default=0)
    status =models.BooleanField(default= False)
    created_date = models.DateTimeField(auto_now_add = True)
    updated_data = models.DateTimeField(auto_now= True)
    
    class Meta:
        ordering = ('created_date',)
    def __str__(self):
        return self.title

core/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        
        

core/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accounts"
# Create your views here.

class UserLoginView(LoginView):
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('/')
    fields = "username", "password"  # Fields to display on the login form
    redirect_authenticated_user = True  # Redirect to success URL if user is already authenticated

    def get_success_url(self):
        return reverse_lazy("song:home")  # Redirect to the task list page after successful login
    
class UserRegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('accounts:login')
    

core/song/views.py
from django.shortcuts import render
from django.shortcuts import redirect, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView
from django.views import View
from song.models import Song, Artist
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.



class HomeList(ListView):
    # model = Artist
    context_object_name = "all_artist"
    template_name = "song/index.html"
    queryset = Artist.objects.filter(status = True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["all_songs"] = Song.objects.filter(status=1)
        return context
    
class AllSong(ListView):
    model = Song
    context_object_name = "all_song"
    template_name = "song/all-song.html"
    
class PlaySong(DetailView):
    template_name='song/detail.html'
    context_object_name = 'song'
    
    
    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        song = get_object_or_404(Song, pk=pk)
        return song
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        song = self.get_object()
        context["all_songs"] = Song.objects.filter(status=True, artist=song.artist)
        return context
  
        
        
class ChoiceArtist(View):
    def get(self, request, artist_id):
        artist = get_object_or_404(Artist, pk= artist_id)
        songs = Song.objects.filter(artist=artist.id)
        context = {'all_songs':songs}
        return render (request , 'song/songs.html',context)
    
class Searchview(View):
    def get(self,request):
        songs = Song.objects.filter(status=1)
        q = request.GET.get('q')
        songs = songs.filter(title__icontains=q)
        context = {'all_song':songs}
        return render (request , "song/all-song.html",context)


'''class ArtistCreateView(LoginRequiredMixin, CreateView):
    model = Artist
    template_name = 'song/createartist.html'
    fields = ['image', 'name']
    success_url = reverse_lazy('song:home')

    def form_valid(self, form):
        artist = form.save(commit=False)
        artist.status = False
        artist.save()
        return super().form_valid(form)
    

class SongCreateView(LoginRequiredMixin, CreateView):
    model = Song
    template_name = 'song/createsong.html'
    fields = ['image', 'title',"artist","audio","lyric"]
    success_url = reverse_lazy('song:home')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(SongCreateView, self).form_valid(form)
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["artist"] = Artist.objects.filter(status=True)
        return context
    
'''

core/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}

<h2>Login</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>
{% endblock %}

core/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block body %}
	
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}

core/accounts/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Star Tunes | Star Wars Music Player</title>
	
	<!--loads the path to static files such as stylesheets and/or scripts-->
	{% load static %}

	<!-- Materialize CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.2/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
	<link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'song/style.css' %}" />

	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
	<!--Start of NavBar-->
	<nav id="layOut">
	    <div class="nav-wrapper container">

	      <a href="{% url 'song:home' %}" class="brand-logo center hide-on-med-and-down" id="layOut"><i class="fa fa-rebel" id="fontAwIcon" aria-hidden="true"></i>Home</a>
	      <a href="" class="brand-logo center hide-on-large-only show-on-medium-and-down" id="layOut"><i class="fa fa-rebel" id="fontAwIcon" aria-hidden="true"></i>ST</a>
	      <a href="#" data-target="mobile-demo" class="sidenav-trigger left" id="layOut"><i class="material-icons">menu</i></a>
	      <a href="#" data-target="mobile-demo" class="sidenav-trigger show-on-large hide-on-med-and-down right" id="layOut"><i class="material-icons">menu</i></a>
	      <form class="left hide-on-med-and-down">
	        <div class="input-field">
	          <input id="search" type="search" required>
	          <label class="label-icon" for="search"><i class="material-icons">search</i></label>
	         
	        </div>
	      </form>
	      <ul class="sidenav" id="mobile-demo">
	        <li><a href="{% url 'song:home' %}" id="layOut"><i class="material-icons">album</i>Albums</a></li>
	        <li><a href="{% url 'song:all_song' %}" id="layOut"><i class="material-icons">music_note</i>Songs</a></li>
			{% if request.user.is_authenticated %}
			<li><a href="{% url 'accounts:logout' %}" id="layOut"><i class="material-icons">power_settings_new</i>Log Out</a></li>
			{% else %}
			<li><a href="{% url 'accounts:login' %}" id="layOut"><i class="material-icons">power_settings_new</i>Log In</a></li>
			<li><a href="{% url 'accounts:register' %}" id="layOut"><i class="material-icons">power_settings_new</i>Register</a></li>
        	{% endif %}
      
	        
	      </ul>
	    </div>
	  </nav>
	  <main class="container">
	  	<!--Dynamic content blocks from throughout the site-->
	  	{% block body %}


	  	{% endblock %}


		</main>
	<div class="hide-on-large-only">
	<h4 class="center">Search For a Song/Album</h4>
	  	<br>
	  	<form>
	        <div class="input-field">
	          <input class="mobileSearch" id="search" type="search" required>
	          <label class="label-icon" for="search"><i class="material-icons">search</i></label>
	          <i class="material-icons">close</i>
	        </div>
	      </form>
	</div>
	<!-- UIkit JS -->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.2/js/materialize.min.js"></script>
	<script type="text/javascript" src="{% static 'song/init.js' %}"></script>
</body>
</html>

core/song/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Star Tunes | Star Wars Music Player</title>
	
	<!--loads the path to static files such as stylesheets and/or scripts-->
	{% load static %}

	<!-- Materialize CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.2/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
	<link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'song/style.css' %}" />

	<!--Let browser know website is optimized for mobile-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>
	<!--Start of NavBar-->
	<nav id="layOut">
	    <div class="nav-wrapper container">

	      <a href="{% url 'song:home' %}" class="brand-logo center hide-on-med-and-down" id="layOut"><i class="fa fa-rebel" id="fontAwIcon" aria-hidden="true"></i>Home</a>
	      <a href="" class="brand-logo center hide-on-large-only show-on-medium-and-down" id="layOut"><i class="fa fa-rebel" id="fontAwIcon" aria-hidden="true"></i>ST</a>
	      <a href="#" data-target="mobile-demo" class="sidenav-trigger left" id="layOut"><i class="material-icons">menu</i></a>
	      <a href="#" data-target="mobile-demo" class="sidenav-trigger show-on-large hide-on-med-and-down right" id="layOut"><i class="material-icons">menu</i></a>
	      <form class="left hide-on-med-and-down" id="search_form" name="gs" method="GET" action="{% url 'song:search' %}">
	        <div class="input-field">
	          <input id="search" type="search" type="text" name="q" required>
	          <label class="label-icon" for="search"><i class="material-icons">search</i></label>
	         
	        </div>
	      </form>
	      <ul class="sidenav" id="mobile-demo">
	        <li><a href="{% url 'song:home' %}" id="layOut"><i class="material-icons">album</i>Albums</a></li>
	        <li><a href="{% url 'song:all_song' %}" id="layOut"><i class="material-icons">music_note</i>Songs</a></li>
			{% if request.user.is_authenticated %}
			<li><a href="" id="layOut"><i class="material-icons"></i>{{request.user.username}}</a></li>
			<li><a href="{% url 'accounts:logout' %}" id="layOut"><i class="material-icons">power_settings_new</i>Log Out</a></li>
			{% else %}
			<li><a href="{% url 'accounts:login' %}" id="layOut"><i class="material-icons">power_settings_new</i>Log In</a></li>
			<li><a href="{% url 'accounts:register' %}" id="layOut"><i class="material-icons">power_settings_new</i>Register</a></li>
        	{% endif %}
	        
	      </ul>
	    </div>
	  </nav>
	  <main class="container">
	  	<!--Dynamic content blocks from throughout the site-->
	  	{% block body %}


	  	{% endblock %}


		</main>
	<div class="hide-on-large-only">
	<h4 class="center">Search For a Song/Album</h4>
	  	<br>
	  	<form>
	        <div class="input-field">
	          <input class="mobileSearch" id="search" type="search" required>
	          <label class="label-icon" for="search"><i class="material-icons">search</i></label>
	          <i class="material-icons">close</i>
	        </div>
	      </form>
	</div>
	<!-- UIkit JS -->
	<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-alpha.2/js/materialize.min.js"></script>
	<script type="text/javascript" src="{% static 'song/init.js' %}"></script>
</body>
</html>

core/song/templates/song/all-song.html
{% extends 'base.html' %}

{% block body %}
	
	
	<h3>Here are all of the all songs:</h3>

	<div class="row">
    	{% for song in all_song %}
    	<div class="col s12 m6 l4">
    		
	      <div class="card">
	        <div class="card-image">
	     
            <a href="{% url 'song:play_song' song.id %}"><img src="{{ song.image.url }} " alt="" style="width: 250px; height: 250px;" ></a>
	        </div>
	        <div class="card-content">
	        	<span class="card-title truncate">{{ song.artist }}</span>
				<p>{{ song.title }}</p>
				
	          
	         
	        </div>
	      </div>
	      
    	</div>
    	{% endfor %}
  </div>

{% endblock %}

core/song/templates/song/detail.html
{% extends 'base.html' %}

{% block body %}
<br>
<div class="row">
	<div class="col s12 m6 offset-m3 l4">
	      <div class="card">
	        <div class="card-image">
				<a href=""><img src="{{ song.image.url }} " alt=""></a>
	        </div>
	        <div class="card-content">
	        	<ul class="collapsible">
    				<li class="active">
    					<div class="collapsible-header">
	        		<span class="card-title truncate">{{ song.artist }}</span>
	        			</div>
	        			<div class="collapsible-body">
	        			<span class="card-title">{{ song.title }}</span>
	        			</div>
	        		</li>
	        	
	       
	        	</ul>
	       
	        </div>
	      </div>
	      
    </div>
<!--
<img src="{{ album.album_logo }}" alt="{{ album.album_title }}, by {{ album.artist }}">

<h3>{{ album.album_title }}</h3>
<h4>{{ album.artist }}</h4>
-->
<!--
{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}
-->
	<div class="col s12 m12 l8">
	<div class="row">
		<audio controls=""  name="media" style="margin-left: 20px;margin-bottom: 10px;width: 600px;height:50px"><source src="{{song.audio.url}}" type="audio/mpeg" ></audio>
	</div>
	<div class="lyric-container">
		{{ song.lyric|safe }}
	</div>
	</div>
	
			
		</tbody>
	</table>
	<!--
{% for song in album.song_set.all %}
		<input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
		<label for="song{{ forloop.counter }}">
			{{ song.song_title }}
			{% if song.is_favorite %}
				<img src="http://icons.iconarchive.com/icons/3xhumed/star-wars-the-old-republic/16/Star-Wars-The-Old-Republic-8-icon.png" alt="This is a favorite song" />
			{% endif %}
		</label>
		<br>
	{% endfor %}
	-->
</div>
<div class="row">
	{% for song in all_songs %}
	<div class="col s12 m6 l4">
		
	  <div class="card">
		<div class="card-image">
	 
		<a href="{% url 'song:play_song' song.id %}"><img src="{{ song.image.url }} " alt="" style="width: 250px; height: 250px;"></a>
		</div>
		<div class="card-content">
			<span class="card-title truncate">{{ song.artist }}</span>
			<p>{{ song.title }}</p>
		  
		 
		</div>
	  </div>
	  
	</div>
	{% endfor %}
</div>
{% endblock %}

core/song/templates/song/index.html
{% extends 'base.html' %}

{% block body %}
	
	
	<h3>Here are all of the Artist:</h3>

	<div class="row">
    	{% for artist in all_artist %}
    	<div class="col s12 m6 l4">
    		
	      <div class="card">
	        <div class="card-image">
	     
            <a href="{% url 'song:artist_choice' artist.id %}"><img src="{{ artist.image.url }} " alt="" style="width: 250px; height: 250px;"></a>
	        </div>
	        <div class="card-content">
	        	<span class="card-title truncate">{{ artist.name }}</span>
	      
	          
	         
	        </div>
	      </div>
	      
    	</div>
    	{% endfor %}
  </div>

{% endblock %}

core/song/templates/song/songs.html
{% extends 'base.html' %}

{% block body %}
	
	
	<h3>Here are all of the Songs:</h3>

	<div class="row">
    	{% for song in all_songs %}
    	<div class="col s12 m6 l4">
    		
	      <div class="card">
	        <div class="card-image">
	     
            <a href="{% url 'song:play_song' song.id %}"><img src="{{ song.image.url }} " alt="" style="width: 250px; height: 250px;"></a>
	        </div>
	        <div class="card-content">
	        	<span class="card-title truncate">{{ song.artist }}</span>
	        	<p>{{ song.title }}</p>
	          
	         
	        </div>
	      </div>
	      
    	</div>
    	{% endfor %}
  </div>

{% endblock %}